nelmio_api_doc:
    documentation:
        info:
            title: "SNMP Dashboard API"
            description: "Dokumentacja API dla SNMP Dashboard"
            version: "1.0.0"
    areas:
        path_patterns:
            - ^/api
            - ^/dashboard
            - ^/configuration
            - ^/snmp
            - ^/security
            - ^/users
