# config/packages/security.yaml

security:
    # Domyślny hasher haseł
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    # Dostawca użytkowników (encja User)
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    # Firewalle
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: app_user_provider

            # Standardowy formularz logowania
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: /dashboard
                always_use_default_target_path: true

            # Wylogowanie
            logout:
                path: app_logout
                target: app_login

    # Kontrola dostępu
    access_control:
        - { path: ^/snmp, roles: ROLE_USER }
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/configuration, roles: ROLE_USER }
        - { path: ^/users, roles: ROLE_ADMIN }