security:
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username  # Upewnij się, że to właściwe pole!

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            stateless: false
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_dashboard  # Gdzie przekierować po logowaniu
                enable_csrf: true
                username_parameter: _username
                password_parameter: _password

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\AppAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/dashboard, roles: ROLE_USER }
